// react-app/src/components/Counter.js
import React from 'react';
import { connect } from 'react-redux';
import '../css/Counter.css';

class Counter extends React.Component {
    handleIncrement = () => {
        this.props.increment(this.props.count + 1);
    }

    render() {
        return (
            <aside>
                {
                    this.props.count > 0 && (
                        <span>
                            { this.props.count }
                        </span>
                    )
                }

                <button type="button" onClick={ this.handleIncrement }>
                    Increment
                </button>
            </aside>
        );
    }
}

const mapStateToProps = (count) => ({ count });
  
const mapDispatchToProps = (dispatch) => ({
    increment: () => dispatch({ type: 'INCREMENT' })
});

export default connect(mapStateToProps, mapDispatchToProps)(Counter);

// angular-app/src/app/components/counter/counter.component.ts
import { Component } from '@angular/core';
import { Store, select } from '@ngrx/store';
import { increment } from '../../store/counter.actions';
import { Observable } from 'rxjs';

@Component({
    selector: 'app-counter',
    templateUrl: './counter.component.html',
    styleUrls: ['./counter.component.css'],
})
export class CounterComponent {
    count$: Observable<number>;

    constructor(private store: Store<{ count: number }>) {
        this.count$ = store.pipe(select('count'));
    }

    handleIncrement(): void {
        this.store.dispatch(increment());
    }
}

<aside>
    <span *ngIf="(count$ | async) > 0">
        {{ count$ | async }}
    </span>

    <button type="button" (click)="handleIncrement()">
        Increment
    </button>
</aside>
