// angular-app/src/app/components/container/container.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-container',
    templateUrl: './container.component.html',
    styleUrls: ['./container.component.css'],
})
export default class ContainerComponent {
    onIncrement(count: number): void {
        console.log(`The count is ${ count }.`);
    }
}

<div>
    <app-counter
        [default]="0"
        (increment)="onIncrement($event)"
    ></app-counter>
</div>

// vue-app/src/components/container.vue
<template>
    <div>
        <counter :default="0" @increment="onIncrement" />
    </div>
</template>

<script>
import Counter from './counter';

export default {
    components: {
        Counter,
    },

    methods: {
        onIncrement(count) {
            console.log(`The count is ${ count }.`);
        },
    }
};
</script>

<style>
    div {
        padding: 10px;
    }
</style>
